#index:
#    path: /api
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login
    methods: ['POST']

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }